api/urls.py
from django.urls import include, path
from api.views.organisateur import OrganisateurViewSet
from api.views.manifestation import ManifestationAutorisationViewSet, ManifestationDeclarationViewSet
from api.views.manif import InstructionViewSet
from rest_framework import routers


app_name = 'api'
router = routers.DefaultRouter()
# router.register(r'manifestations', api_views.ManifestationAllViewSet)
router.register(r'Instruction', InstructionViewSet, basename='Instruction')
router.register(r'ManifestationAutorisation', ManifestationAutorisationViewSet, basename='ManifestationAutorisation')
router.register(r'ManifestationDeclaration', ManifestationDeclarationViewSet, basename='ManifestationDeclaration')
router.register(r'Organisateur', OrganisateurViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

configuration/urls.py
import debug_toolbar
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.http import HttpResponseBadRequest

from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap

from core.views.ajax import validate_form
from core.views.user import (ProfileDetailView, UserUpdateView, signupagentview, signuporganisateurview,
                             EmailConfirmedView, NomPrenomChange, PasswordExpired, PasswordChangeCustomView, RenvoiMailConfirm)
from core.views.media import media_access
from organisateurs.views import StructureUpdateView
from portail.views.index import HomePage

# Todo : à supprimer après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
from aide import views

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}
handler400 = 'portail.views.erreur400view'
handler403 = 'portail.views.erreur403view'
handler404 = 'portail.views.erreur404view'
handler500 = 'portail.views.erreur500view'

urlpatterns = [
    # Examples:
    # path('', 'ddcs_loire.views.home', name='home'),
    # path('blog/', include('blog.urls')),

    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap\.xml', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    path('accounts/signup/', HttpResponseBadRequest),
    path('accounts/password/change/', PasswordChangeCustomView.as_view(), name='password_change_custom'),
    path('accounts/', include('allauth.urls')),
    path('accounts/passwordexpired', PasswordExpired.as_view(), name="password_expired"),
    path('accounts/send_confirm_mail/<int:pk>/', RenvoiMailConfirm.as_view(), name="send_confirm_mail"),
    path('accounts/email_confirmed', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('accounts/profile/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile/edit', UserUpdateView.as_view(), name='profile_edit'),
    path('accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    path('accounts/profilte/name', NomPrenomChange.as_view(), name="nom_prenom_change"),
    path('inscription/agent', signupagentview, name='inscription_agent'),
    path('inscription/organisateur', signuporganisateurview, name='inscription_organisateur'),
    path('administration/', include('administration.urls')),
    path('agreements/', include('agreements.urls')),
    path('carto/', include('carto.urls')),
    path('sub_agreements/', include('sub_agreements.urls')),
    path('instructions/', include('instructions.urls')),
    path('authorizations/', include('authorizations.urls')),
    path('declarations/', include('declarations.urls')),
    path('evaluations/', include('evaluations.urls')),
    path('incidence/', include('evaluation_incidence.urls')),
    path('notifications/', include('notifications.urls')),
    path('nouveautes/', include('nouveautes.urls')),
    path('sports/', include('sports.urls')),
    path('administrative_division/', include('administrative_division.urls')),
    path('', include('events.urls')),
    path('', include('evenements.urls')),
    path('protected_areas/', include('protected_areas.urls')),
    re_path('validate/(?P<alias>[\w\-]+)/', validate_form, name='validate'),
    path('ajax_select/', include('ajax_select.urls')),
    path('', include('portail.urls')),
    path('', HomePage.as_view(), name='home_page'),
    path('aide/', include('aide.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    # Todo : à réactiver après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
    # Todo : à supprimer après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
    #re_path('(?P<path>.+)', views.view_help_page, name="help-page"),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)', media_access, name='media'),

# Les flatpages doivent être toujours après les média pour eviter une interceptions des demandes de media
urlpatterns += path('', include('django.contrib.flatpages.urls')),

evaluations/urls.py
# coding: utf-8

from django.urls import path, re_path

from evaluations.views import Natura2000EvaluationCreate, Natura2000EvalCreate, Natura2000EvaluationUpdate
from evaluations.views import RNREvaluationCreate, RNREvalCreate, RNREvaluationUpdate


app_name = 'evaluations'
urlpatterns = [
    # Évaluations
    re_path('natura2000evaluation/add/(?P<manifestation_pk>\d+)/', Natura2000EvaluationCreate.as_view(), name='natura2000evaluation_add'),
    re_path('natura2000eval/add/(?P<pk>\d+)/', Natura2000EvalCreate.as_view(), name='natura2000eval_add'),
    re_path('natura2000evaluation/(?P<pk>\d+)/edit/', Natura2000EvaluationUpdate.as_view(), name='natura2000evaluation_update'),
    re_path('rnrevaluation/add/(?P<manifestation_pk>\d+)/', RNREvaluationCreate.as_view(), name='rnrevaluation_add'),
    re_path('rnreval/add/(?P<pk>\d+)/', RNREvalCreate.as_view(), name='rnreval_add'),
    re_path('rnrevaluation/(?P<pk>\d+)/edit/', RNREvaluationUpdate.as_view(), name='rnrevaluation_update'),
]

evaluations/models/evaluation.py
# coding: utf-8
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

from events.models import Manifestation
from evenements.models import Manif


class EvaluationManifestation(models.Model):
    """ Évaluation de l'impact environnemental d'une manifestation """

    # Constantes
    COST_CHOICES = (('0', "moins de 5 000 €"), ('1', "entre 5 000 et 20 000 €"), ('2', "entre 20 000 et 100 000 €"), ('3', "plus de 100 000 €"))
    IMPACT_CHOICES = (('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'))

    # Champs
    content_type = models.ForeignKey(ContentType, null=True, blank=True, on_delete=models.SET_NULL)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey()
    manifestation = models.OneToOneField(Manifestation, verbose_name='manifestation', on_delete=models.CASCADE, null=True)
    manif = models.OneToOneField(Manif, verbose_name='manif', on_delete=models.CASCADE, null=True)
    # Description
    place = models.CharField("lieu-dit", max_length=255, blank=True)
    # Fréquence de la manifestation
    every_year = models.BooleanField("la manifestation a lieu chaque année", default=False)
    first_edition = models.BooleanField("première édition de la manifestation", default=False)
    other_frequency = models.CharField("autre fréquence", max_length=255, blank=True)
    # Budget
    cost = models.CharField("coût de la manifestation", max_length=1, choices=COST_CHOICES)
    # Localization
    track_total_length = models.PositiveIntegerField("longueur totale des parcours (km)")
    # Éuipements et installations liés
    night_lighting = models.BooleanField("éclairage nocturne", default=False)
    night_lighting_desc = models.TextField("description", blank=True)
    trails_marks = models.BooleanField(
        "balisage des sentiers", default=False,
        help_text="Seuls les balisages temporaires retirés sous 24h sont autorisés dans le "
                  "cadre de manifestations sportives. Par conséquent ne seront pas autorisés "
                  "l'usage de peinture, confettis ou tout autre type de balisage laissant une "
                  "empreinte sur les milieux",
    )
    trails_marks_desc = models.TextField('description', blank=True)
    other_facilities = models.BooleanField("autres types d'aménagements", default=False)
    other_facilities_desc = models.TextField('description', blank=True)
    # Potential implications
    noise_emissions = models.BooleanField(
        "les émissions sonores sont susceptibles de déranger les espèces présentes "
        "sur le site (puissance des émissions et proximité du site)",
        default=False,
        help_text="Le bruit peut entraîner le dérangement de certaines espèces animales, "
                  "notamment en période de nidification ou d’hivernage pour les oiseaux.",
    )
    waste_management = models.BooleanField(
        "vous avez prévu des dispositifs particuliers pour la gestion des déchets "
        "pendant et après la manifestation [À décrire dans le champ réservé]",
        default=False,
        help_text="Les déchets polluent le milieu naturel et représentent un danger pour les "
                  "espèces animales (risque d’ingestion notamment).",
    )
    waste_management_desc = models.TextField('description', blank=True)
    awareness = models.BooleanField(
        "vous avez prévu la mise en place d'actions de communication ou de "
        "sensibilisation concernant les enjeux environnementaux",
        default=False,
        help_text="La sensibilisation et la communication permettent de réduire les impacts sur "
                  "l’environnement. Contacter l’animateur du site pour la réalisation ou la "
                  "mise à disposition de documents de communication.",
    )
    impact_reduction = models.BooleanField(
        "vous avez pris des mesures pour réduire l'impact de la manifestation sur le "
        "milieu naturel (contacts structures, choix du lieu en fonction des enjeux, "
        "délimitation de zones interdites au public...) [À décrire dans le champ "
        "réservé]",
        default=False,
        help_text="réduction des impacts",
    )
    impact_reduction_desc = models.TextField('description', blank=True)
    # Conclusions
    estimated_impact = models.CharField(
        "impact estimé de la manifestation",
        max_length=1,
        choices=IMPACT_CHOICES,
        help_text="D'après les éléments mis en évidence dans ce formulaire, évaluer l'impact de "
                  "la manifestation en donnant un chiffre de 0 à 5 (0 correspondant à une "
                  "absence d'incidences et 5 à une incidence significative sur le ou les sites "
                  "concernés)",
    )

    # Getter
    def get_absolute_url(self):
        """ Renvoyer l'URL de consultation du contenu """
        if self.manifestation:
            return Manifestation.objects.get_subclass(id=self.manifestation.id).get_absolute_url()
        return Manif.objects.get_subclass(id=self.manif.id).get_absolute_url()

    # Méta
    class Meta:
        abstract = True
        verbose_name = "évaluation d'une manifestation"
        verbose_name_plural = "évaluations de manifestations"
        app_label = 'evaluations'

evaluations/models/rnr.py
# coding: utf-8
from django.db import models
from django.utils.encoding import smart_text

from evaluations.models.evaluation import EvaluationManifestation


class RNREvaluation(EvaluationManifestation):
    """ Évalutation réserve naturelle régionale """

    # Constantes
    DURATION_CHOICES = (
        ('1', "demande d'autorisation pour 1 année"),
        ('3', "demande d'autorisation pour 3 années avec engagement de non modification des parcours et des conditions d'organisation"),
    )
    # Frequency
    request_duration = models.CharField("durée de la demande d'autorisation", max_length=1, choices=DURATION_CHOICES)
    # Localization
    sites = models.ManyToManyField('protected_areas.rnr', verbose_name="sites RNR concernés")
    # Attendance
    rnr_entries = models.PositiveIntegerField("participants concernés par le passage dans la RNR")
    rnr_audience = models.PositiveIntegerField("spectateurs concernés par le passage dans la RNR")
    # Provisions taken
    administrator_contact_date = models.DateField("date de contact avec les gestionnaires de la réserve")
    sensitization = models.CharField("dispositif de sensibilisation à l'environnement et à la réserve envisagé", max_length=255)
    forbidden_areas = models.CharField("dispositif de canalisation du public", max_length=255)
    administrator_attendance = models.BooleanField(
        "l’organisateur souhaite la présence du gestionnaire de la RNR lors de la "
        "manifestation",
        default=False
    )
    # Potential implications
    plane_attendance = models.BooleanField("il y aura présence d'engins aériens [À décrire dans le champ réservé]", default=False)
    plane_attendance_desc = models.TextField("dispositif pour la gestion des engins aériens", blank=True)
    trampling = models.BooleanField("la présence des participants et du public entraînera un piétinement des sols "
                                    "[À décrire dans le champ réservé]", default=False)
    trampling_desc = models.TextField("dispositif pour la gestion du piétinement", blank=True)
    markup = models.BooleanField("vous avez prévu un balisage, une signalisation spécifique à la manifestation "
                                 "[À décrire dans le champ réservé]", default=False)
    markup_desc = models.TextField("dispositif pour la gestion du balisage et de la signalisation", blank=True)
    # Conclusion
    regulatory_compliance = models.BooleanField(
        "le projet, la manifestation respecte bien la réglementation propre à la réserve",
        default=False,
        help_text="voir encadré ci-dessus"
    )
    rnr_conclusion = models.BooleanField("ce formulaire permet de conclure à l'absence d'incidence significative sur "
                                         "le ou les sites RNR concernés par la manifestation", default=False)

    # Overrides
    def __str__(self):
        if self.manifestation:
            return smart_text(self.manifestation.__str__())
        return smart_text(self.manif.__str__())

    # Méta
    class Meta(EvaluationManifestation.Meta):
        verbose_name = "évaluation RNR"
        verbose_name_plural = "évaluations RNR"
        default_related_name = "rnrevaluations"
        app_label = "evaluations"

evaluations/templates/evaluations/evaluation_detail.html
{% load i18n %}

{% block maj %}{% endblock %}

<div class="card-header">
    {% block associated_evaluation %}
    {% endblock %}
</div>
<ul class="list-group mb-3">
    <li class="list-group-item">Lieu-dit : {{ evaluation.place|capfirst }}</li>
    {% block daynight %}
    {% endblock %}
</ul>


<div class="card-header">
    <i class="date"></i>Fréquence de la manifestation
</div>
<ul class="list-group mb-3">
    {% if evaluation.every_year %}
        <li class="list-group-item">La manifestation a lieu chaque année : {{ evaluation.every_year|yesno|title }}</li>
    {% endif %}
    {% if evaluation.first_edition %}
        <li class="list-group-item">Première édition de la manifestation : {{ evaluation.first_edition|yesno|title }}</li>
    {% endif %}
    {% if evaluation.other_frequency %}
        <li class="list-group-item">Autre fréquence : {{ evaluation.other_frequency|capfirst }}</li>
    {% endif %}
    {% block frequency %}
    {% endblock %}
</ul>


{% block attendance %}
{% endblock %}


<div class="card-header">
    <i class="euro"></i> Budget de la manifestation
</div>
<ul class="list-group mb-3">
    <li class="list-group-item">Coût de la manifestation : {{ evaluation.get_cost_display }}</li>
</ul>


<div class="card-header">
    {% if evaluation.rnr_entries %}
        <i class="carto"></i> Localisation de la manifestation par rapport aux sites RNR
    {% else %}
        <i class="carto"></i> Localisation de la manifestation par rapport aux sites Natura 2000
    {% endif %}
</div>
<ul class="list-group mb-3">
    <li class="list-group-item">Longueur totale des parcours en RNR : {{ evaluation.track_total_length }}</li>
</ul>

{% block sites %}
{% endblock %}

{% block provisions_taken %}
{% endblock %}

{% block area_of_influence %}
{% endblock %}

{% block natural_habitats %}
{% endblock %}

{% block species %}
{% endblock %}

<div class="card-header">
    Présence d'aménagements connexes
</div>
    <ul class="list-group mb-3">
    {% if evaluation.parking_lot or evaluation.parking_lot_desc %}
        <li class="list-group-item">Parking : {{ evaluation.parking_lot|yesno|title }}
            {% if evaluation.parking_lot_desc %}
                - {{ evaluation.parking_lot_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
    {% if evaluation.reception_area or evaluation.reception_area_desc %}
        <li class="list-group-item">Zone d'accueil du public/des spéctateurs : {{ evaluation.reception_area|yesno|title }}
            {% if evaluation.reception_area_desc %}
                - {{ evaluation.reception_area_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
    {% if evaluation.supplying_area or evaluation.supplying_area_desc %}
        <li class="list-group-item">Zones de ravitaillement : {{ evaluation.supplying_area|yesno|title }}
        {% if evaluation.supplying_area_desc %}
            - {{ evaluation.supplying_area_desc|capfirst }}
        {% endif %}
        </li>
    {% endif %}
    {% if evaluation.storage_area or evaluation.storage_area_desc %}
        <li class="list-group-item">Zone de stockage (matériel, véhicules...) : {{ evaluation.storage_area|yesno|title }}
            {% if evaluation.storage_area_desc %}
                - {{ evaluation.storage_area_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
    {% if evaluation.awards_stage or evaluation.awards_stage_desc %}
        <li class="list-group-item">Scène de remise des prix : {{ evaluation.awards_stage|yesno|title }}
            {% if evaluation.awards_stage_desc %}
                - {{ evaluation.awards_stage_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
    {% if evaluation.bivouac_area or evaluation.bivouac_area_desc %}
        <li class="list-group-item">Zone de bivouac : {{ evaluation.bivouac_area|yesno|title }}
            {% if evaluation.bivouac_area_desc %}
                - {{ evaluation.bivouac_area_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
    {% if evaluation.noise or evaluation.noise_desc %}
        <li class="list-group-item">Émissions sonores (sono, concert...) : {{ evaluation.noise|yesno|title }}
            {% if evaluation.noise_desc %}
                - {{ evaluation.noise_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
    {% if evaluation.night_lighting or evaluation.night_lighting_desc %}
        <li class="list-group-item">Éclairage nocturne : {{ evaluation.night_lighting|yesno|title }}
            {% if evaluation.night_lighting_desc %}
                - {{ evaluation.night_lighting_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
    {% if evaluation.trails_marks or evaluation.trails_marks_desc %}
        <li class="list-group-item">Balisage des sentiers : {{ evaluation.trails_marks|yesno|title }}
            {% if evaluation.trails_marks_desc %}
            - {{ evaluation.trails_marks_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
    {% if evaluation.other_facilities or evaluation.other_facilities_desc %}
        <li class="list-group-item">Autres types d'aménagements : {{ evaluation.other_facilities|yesno|title }}
            {% if evaluation.other_facilities_desc %}
            - {{ evaluation.other_facilities_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
</ul>


<div class="card-header">
        {% if evaluation.rnr_conclusion %}
            Incidences potentielles sur RNR
        {% else %}
            Incidences potentielles sur Natura 2000
        {% endif %}
</div>
<ul class="list-group mb-3">
    {% if evaluation.water_crossing %}
        <li class="list-group-item">Franchissement d'un cours d'eau hors d'un passage aménagé : {{ evaluation.water_crossing|yesno|title }}</li>
    {% endif %}
    {% if evaluation.off_trail %}
        <li class="list-group-item">Passage des participants en dehors des sentiers (à localiser sur la carte) : {{ evaluation.off_trail|yesno|title }}</li>
    {% endif %}
    {% if evaluation.bio_implications %}
        <li class="list-group-item">La présence du public est susceptible d'avoir une incidence sur les habitats
            naturels et/ou les espèces animales et végétales : {{ evaluation.bio_implications|yesno|title }}</li>
    {% endif %}
    {% if evaluation.related_facilities %}
        <li class="list-group-item">Présence d'aménagements connexes : {{ evaluation.related_facilities|yesno|title }}</li>
    {% endif %}
    {% if evaluation.noise_emissions %}
        <li class="list-group-item">Les émissions sonores sont susceptibles de déranger les espèces présentes
            sur le site (puissance des émissions et proximité du site) : {{ evaluation.noise_emissions|yesno|title }}</li>
    {% endif %}
    {% if evaluation.light_emissions %}
    <li class="list-group-item">Les émissions lumineuses nocturnes sont-elles susceptibles de déranger les
        espèces présentes sur le site : {{ evaluation.light_emissions|yesno|title }}</li>
    {% endif %}
    {% if evaluation.waste_management or evaluation.waste_management_desc %}
        <li class="list-group-item">Vous avez prévu des dispositifs particuliers pour la gestion des déchets
            pendant et après la manifestation [À décrire dans le champ réservé] : {{ evaluation.waste_management|yesno|title }}
            {% if evaluation.waste_management_desc %}
                - {{ evaluation.waste_management_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
    {% if evaluation.awareness %}
        <li class="list-group-item">Vous avez prévu la mise en place d'actions de communication ou de
            sensibilisation concernant les enjeux environnementaux : {{ evaluation.awareness|yesno|title }}</li>
    {% endif %}
    {% if evaluation.impact_reduction or evaluation.impact_reduction_desc %}
        <li class="list-group-item">Vous avez pris des mesures pour réduire l'impact de la manifestation sur le
            milieu naturel (contacts structures, choix du lieu en fonction des enjeux,
            délimitation de zones interdites au public...) [À décrire dans le champ réservé] : {{ evaluation.impact_reduction|yesno|title }}
            {% if evaluation.impact_reduction_desc %}
                - {{ evaluation.impact_reduction_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
    {% block potential_implications %}
    {% endblock %}
</ul>

<div class="card-header">
    Conclusions
</div>
<ul class="list-group mb-3">
    {% block conclusion %}
        <li class="list-group-item">Impact estimé de la manifestation : {{ evaluation.estimated_impact|capfirst }}</li>
    {% endblock %}
</ul>

evaluations/templates/evaluations/n2kevaluation_form.html
{% extends "base_form.html" %}

{% load i18n static %}

{% block head_title %}Formulaire d'évaluation Natura 2000{% endblock %}
{% block page_title %}
    <h1>Formulaire d'évaluation Natura 2000</h1>
{% endblock %}

{% block extra_js %}
    <script src='{% static 'libs/autogrow/jquery.ns-autogrow.min.js' %}' type="text/javascript"></script>
    <script src='{% static 'evaluations/js/evaluation-form.js' %}' type="text/javascript"></script>
{% endblock %}

evaluations/templates/evaluations/rnrevaluation_detail.html
{% extends "evaluations/evaluation_detail.html" %}

{% load i18n %}

{% block maj %}
    {% ifequal user object.structure.organisateur.user %}
        {% if not object.processing and not export %}
            <div class="card-body text-right">
                <a href="{% url 'evaluations:rnrevaluation_update' evaluation.pk %}"
                   class="btn btn-primary" role="button">Mettre à jour
                </a>
            </div>
        {% endif %}
    {% endifequal %}
{% endblock %}

{% block associated_evaluation %}
    Évaluation RNR associée
{% endblock %}

{% block sites %}
    {% if evaluation.sites.first %}
        <div class="card-header">
            Sites RNR concernés
        </div>
        <ul class="list-group mb-3">
            {% for site in evaluation.sites.all %}
                <li class="list-group-item">- {{ site }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}


{% block frequency %}
    {{ block.super }}
    <li class="list-group-item">Durée de la demande d'autorisation : {{ evaluation.get_request_duration_display|capfirst }}</li>
{% endblock %}


{% block attendance %}
    <div class="card-header">
        Fréquentation
    </div>
    <ul class="list-group mb-3">
        <li class="list-group-item">Participants concernés par le passage dans la RNR : {{ evaluation.rnr_entries }} Personnes</li>
        <li class="list-group-item">Spectateurs concernés par le passage dans la RNR : {{ evaluation.rnr_attendance }} Personnes</li>
    </ul>
{% endblock %}

{% block provisions_taken %}
    <div class="card-header">
        Prise en compte de l'environnement
    </div>
    <ul class="list-group mb-3">
        <li class="list-group-item">Date de contact avec les gestionnaires de la réserve : {{ evaluation.administrator_contact_date }}</li>
        <li class="list-group-item">Dispositif de sensibilisation à l'environnement et à la réserve envisagé : {{ evaluation.sensitization|capfirst }}</li>
        <li class="list-group-item">Dispositif de canalisation du public : {{ evaluation.forbidden_areas }}</li>
        <li class="list-group-item">L’organisateur souhaite la présence du gestionnaire de la RNR lors de la manifestation : {{ evaluation.administrator_attendance|yesno|title }}</li>
    </ul>
{% endblock %}

{% block potential_implications %}
    {{ block.super }}
    {% if evaluation.plane_attendance or evaluation.plane_attendance_desc %}
        <li class="list-group-item">Il y aura présence d'engins aériens [À décrire dans le champ réservé] : {{ evaluation.plane_attendance|yesno|title }}
            {% if evaluation.plane_attendance_desc %}
                - {{ evaluation.plane_attendance_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
    {% if evaluation.trampling or evaluation.trampling_desc %}
        <li class="list-group-item">La présence des participants et du public entraînera un piétinement des sols [À décrire dans le champ réservé] : {{ evaluation.trampling|yesno|title }}
            {% if evaluation.trampling_desc %}
                - {{ evaluation.trampling_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
    {% if evaluation.markup or evaluation.markup_desc %}
        <li class="list-group-item">Vous avez prévu un balisage, une signalisation spécifique à la manifestation
            [À décrire dans le champ réservé] : {{ evaluation.markup|yesno|title }}
            {% if evaluation.markup_desc %}
                - {{ evaluation.markup_desc|capfirst }}
            {% endif %}
        </li>
    {% endif %}
{% endblock %}


{% block conclusion %}
    {{ block.super }}
    <li class="list-group-item">Le projet, la manifestation respecte bien la réglementation propre à la réserve : {{ evaluation.regulatory_compliance|yesno|title }}</li>
    <li class="list-group-item">Ce formulaire permet de conclure à l'absence d'incidence significative sur
        le ou les sites RNR concernés par la manifestation : {{ evaluation.rnr_conclusion|yesno|title }}</li>
{% endblock %}

evaluations/templates/evaluations/rnrevaluation_form.html
{% extends "base_form.html" %}

{% load i18n static %}

{% block head_title %}Localisation de la manifestation par rapport aux sites RNR{% endblock %}
{% block page_title %}
    <h1>Localisation de la manifestation par rapport aux sites RNR</h1>
{% endblock %}

{% block extra_js %}
    <script src='{% static 'libs/autogrow/jquery.ns-autogrow.min.js' %}' type="text/javascript"></script>
    <script src='{% static 'evaluations/js/evaluation-form.js' %}' type="text/javascript"></script>
{% endblock %}