api/urls.py
from django.urls import include, path
from api.views.organisateur import OrganisateurViewSet
from api.views.manifestation import ManifestationAutorisationViewSet, ManifestationDeclarationViewSet
from api.views.manif import InstructionViewSet
from rest_framework import routers


app_name = 'api'
router = routers.DefaultRouter()
# router.register(r'manifestations', api_views.ManifestationAllViewSet)
router.register(r'Instruction', InstructionViewSet, basename='Instruction')
router.register(r'ManifestationAutorisation', ManifestationAutorisationViewSet, basename='ManifestationAutorisation')
router.register(r'ManifestationDeclaration', ManifestationDeclarationViewSet, basename='ManifestationDeclaration')
router.register(r'Organisateur', OrganisateurViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

authorizations/urls.py
# coding: utf-8
from django.urls import path, re_path

from .views import *


app_name = 'authorizations'
urlpatterns = [
    # Dashboard
    path('dashboard/', Dashboard.as_view(), name="dashboard"),
    path('archives/', Archives.as_view(), name="archives"),

    # Autres vues
    re_path('add/(?P<manifestation_pk>\d+)', AuthorizationCreateView.as_view(), name='authorization_add'),
    re_path('(?P<pk>\d+)/publish/', AuthorizationPublishBylawView.as_view(), name='authorization_publish'),
    re_path('(?P<pk>\d+)/edit/', AuthorizationUpdateView.as_view(), name="authorization_update"),
    re_path('(?P<pk>\d+)/', AuthorizationDetailView.as_view(), name="authorization_detail"),
]

configuration/urls.py
import debug_toolbar
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.http import HttpResponseBadRequest

from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap

from core.views.ajax import validate_form
from core.views.user import (ProfileDetailView, UserUpdateView, signupagentview, signuporganisateurview,
                             EmailConfirmedView, NomPrenomChange, PasswordExpired, PasswordChangeCustomView, RenvoiMailConfirm)
from core.views.media import media_access
from organisateurs.views import StructureUpdateView
from portail.views.index import HomePage

# Todo : à supprimer après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
from aide import views

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}
handler400 = 'portail.views.erreur400view'
handler403 = 'portail.views.erreur403view'
handler404 = 'portail.views.erreur404view'
handler500 = 'portail.views.erreur500view'

urlpatterns = [
    # Examples:
    # path('', 'ddcs_loire.views.home', name='home'),
    # path('blog/', include('blog.urls')),

    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap\.xml', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    path('accounts/signup/', HttpResponseBadRequest),
    path('accounts/password/change/', PasswordChangeCustomView.as_view(), name='password_change_custom'),
    path('accounts/', include('allauth.urls')),
    path('accounts/passwordexpired', PasswordExpired.as_view(), name="password_expired"),
    path('accounts/send_confirm_mail/<int:pk>/', RenvoiMailConfirm.as_view(), name="send_confirm_mail"),
    path('accounts/email_confirmed', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('accounts/profile/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile/edit', UserUpdateView.as_view(), name='profile_edit'),
    path('accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    path('accounts/profilte/name', NomPrenomChange.as_view(), name="nom_prenom_change"),
    path('inscription/agent', signupagentview, name='inscription_agent'),
    path('inscription/organisateur', signuporganisateurview, name='inscription_organisateur'),
    path('administration/', include('administration.urls')),
    path('agreements/', include('agreements.urls')),
    path('carto/', include('carto.urls')),
    path('sub_agreements/', include('sub_agreements.urls')),
    path('instructions/', include('instructions.urls')),
    path('authorizations/', include('authorizations.urls')),
    path('declarations/', include('declarations.urls')),
    path('evaluations/', include('evaluations.urls')),
    path('incidence/', include('evaluation_incidence.urls')),
    path('notifications/', include('notifications.urls')),
    path('nouveautes/', include('nouveautes.urls')),
    path('sports/', include('sports.urls')),
    path('administrative_division/', include('administrative_division.urls')),
    path('', include('events.urls')),
    path('', include('evenements.urls')),
    path('protected_areas/', include('protected_areas.urls')),
    re_path('validate/(?P<alias>[\w\-]+)/', validate_form, name='validate'),
    path('ajax_select/', include('ajax_select.urls')),
    path('', include('portail.urls')),
    path('', HomePage.as_view(), name='home_page'),
    path('aide/', include('aide.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    # Todo : à réactiver après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
    # Todo : à supprimer après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
    #re_path('(?P<path>.+)', views.view_help_page, name="help-page"),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)', media_access, name='media'),

# Les flatpages doivent être toujours après les média pour eviter une interceptions des demandes de media
urlpatterns += path('', include('django.contrib.flatpages.urls')),

declarations/urls.py
# coding: utf-8
from django.urls import path, re_path

from .views import DeclarationCreateView, DeclarationDetailView, DeclarationPublishReceiptView
from .views import Dashboard, Archives


app_name = 'declarations'
urlpatterns = [
    path('dashboard/', Dashboard.as_view(), name="dashboard"),
    path('archives/', Archives.as_view(), name="archives"),

    re_path('(?P<pk>\d+)/publish/', DeclarationPublishReceiptView.as_view(), name='declaration_publish'),
    re_path('add/(?P<manifestation_pk>\d+)', DeclarationCreateView.as_view(), name='declaration_add'),
    re_path('(?P<pk>\d+)/', DeclarationDetailView.as_view(), name='declaration_detail')
]

events/urls.py
# coding: utf-8
from django.urls import path, re_path

from events.views.autorisationnm import AutorisationNMFilesUpdate
from events.views.declarationnm import DeclarationNMFilesUpdate
from events.views.motorizedconcentration import MotorizedConcentrationFilesUpdate
from events.views.motorizedmanifestation import MotorizedEventFilesUpdate
from events.views.motorizedrace import MotorizedRaceFilesUpdate
from .views import ManifestationStartChoose
from .views import Dashboard
from .views import UnsupportedManifestationCreate
from .views import ManifestationInstructeurUpdate
from .views import AutorisationNMCreate
from .views import AutorisationNMDetail
from .views import AutorisationNMUpdate
from .views import CreateRoute
from .views import DeclarationNMChoose
from .views import DeclarationNMCreate
from .views import DeclarationNMDetail
from .views import DeclarationNMUpdate
from .views import DocumentComplementaireProvideView
from .views import DocumentComplementaireRequestView
from .views import MailToOrganisateursView
from .views import MailToTownHallsView
from .views import ManifestationChoose
from .views import ManifestationPublicDetail
from .views import MotorizedConcentrationCreate
from .views import MotorizedConcentrationDetail
from .views import MotorizedConcentrationUpdate
from .views import MotorizedEventChoose
from .views import MotorizedEventCreate
from .views import MotorizedEventDetail
from .views import MotorizedEventUpdate
from .views import MotorizedRaceCreate
from .views import MotorizedRaceDetail
from .views import MotorizedRaceUpdate
from .views import NonMotorizedEventChoose
from .views import PublicRoadMotorizedEventChoose
from organisateurs.views import StructureCreate


app_name = 'events'
urlpatterns = [

    # Tableau de bord principal
    path('dashboard/', Dashboard.as_view(), name="dashboard"),

    path('mail_to_promoters/', MailToOrganisateursView.as_view(), name='mail_to_promoters'),
    path('mail_to_townhalls/', MailToTownHallsView.as_view(), name='mail_to_townhalls'),
    path('structure/add', StructureCreate.as_view(), name='structure_add'),

    path('events/choose_start/', ManifestationStartChoose.as_view(), name='manifestation_start_choose'),
    path('events/create_route/', CreateRoute.as_view(), name='create_route'),
    path('events/choose/', ManifestationChoose.as_view(), name='manifestation_choose'),
    path('motorizedevents/choose', MotorizedEventChoose.as_view(), name="motorizedevent_choose"),
    path('nonmotorizedevents/choose', NonMotorizedEventChoose.as_view(), name="nonmotorizedevent_choose"),
    path('DeclarationNM/choose', DeclarationNMChoose.as_view(), name="declarationnm_choose"),
    path('publicroadmotorizedevents/choose', PublicRoadMotorizedEventChoose.as_view(), name="publicroadmotorizedevent_choose"),

    # Manifestation sans type (non supporté)
    path('unsupported/add/', UnsupportedManifestationCreate.as_view(), name="unsupported_manifestation_add"),

    # Modifications instructeur
    re_path('event/(?P<pk>\d+)/instruction/', ManifestationInstructeurUpdate.as_view(), name="manifestation_instructeur"),
    re_path('event/(?P<manifestation_pk>\d+)/additional_data/add', DocumentComplementaireRequestView.as_view(), name="additional_data_add"),
    re_path('event/(?P<pk>\d+)/', ManifestationPublicDetail.as_view(), name="manifestation_detail"),

    # DeclarationNM urls
    path('DeclarationNM/add/', DeclarationNMCreate.as_view(), name="declarationnm_add"),
    re_path('DeclarationNM/(?P<pk>\d+)/edit/', DeclarationNMUpdate.as_view(), name="declarationnm_update"),
    re_path('DeclarationNM/(?P<pk>\d+)/edit_files/', DeclarationNMFilesUpdate.as_view(), name="declarationnm_files_update"),
    re_path('DeclarationNM/(?P<pk>\d+)/', DeclarationNMDetail.as_view(), name="declarationnm_detail"),

    # AutorisationNM urls
    path('AutorisationNM/add/', AutorisationNMCreate.as_view(), name="autorisationnm_add"),
    re_path('AutorisationNM/(?P<pk>\d+)/edit/', AutorisationNMUpdate.as_view(), name="autorisationnm_update"),
    re_path('AutorisationNM/(?P<pk>\d+)/edit_files/', AutorisationNMFilesUpdate.as_view(), name="autorisationnm_files_update"),
    re_path('AutorisationNM/(?P<pk>\d+)/', AutorisationNMDetail.as_view(), name="autorisationnm_detail"),

    # MotorizedConcentration urls
    path('motorizedconcentrations/add/', MotorizedConcentrationCreate.as_view(), name="motorizedconcentration_add"),
    re_path('motorizedconcentrations/(?P<pk>\d+)/edit/', MotorizedConcentrationUpdate.as_view(), name="motorizedconcentration_update"),
    re_path('motorizedconcentrations/(?P<pk>\d+)/edit_files/', MotorizedConcentrationFilesUpdate.as_view(), name="motorizedconcentration_files_update"),
    re_path('motorizedconcentrations/(?P<pk>\d+)/', MotorizedConcentrationDetail.as_view(), name="motorizedconcentration_detail"),

    # MotorizedEvent urls
    path('motorizedevents/add/', MotorizedEventCreate.as_view(), name="motorizedevent_add"),
    re_path('motorizedevents/(?P<pk>\d+)/edit/', MotorizedEventUpdate.as_view(), name="motorizedevent_update"),
    re_path('motorizedevents/(?P<pk>\d+)/edit_files/', MotorizedEventFilesUpdate.as_view(), name="motorizedevent_files_update"),
    re_path('motorizedevents/(?P<pk>\d+)/', MotorizedEventDetail.as_view(), name="motorizedevent_detail"),

    # MotorizedRace urls
    path('motorizedraces/add/', MotorizedRaceCreate.as_view(), name="motorizedrace_add"),
    re_path('motorizedraces/(?P<pk>\d+)/edit/', MotorizedRaceUpdate.as_view(), name="motorizedrace_update"),
    re_path('motorizedraces/(?P<pk>\d+)/edit_files/', MotorizedRaceFilesUpdate.as_view(), name="motorizedrace_files_update"),
    re_path('additional_data/(?P<pk>\d+)/', DocumentComplementaireProvideView.as_view(), name="additional_data_provide"),
    re_path('motorizedraces/(?P<pk>\d+)/', MotorizedRaceDetail.as_view(), name="motorizedrace_detail"),

]

declarations/forms.py
# coding: utf-8
from crispy_forms.bootstrap import FormActions
from crispy_forms.layout import Submit, Layout, Fieldset
from django import forms

from core.forms.base import GenericForm
from .models import ManifestationDeclaration


class DeclarationForm(GenericForm):
    """ Formulaire de déclaration """

    def __init__(self, *args, **kwargs):
        """ Créer le layout du formulaire via crispy_forms """
        super(DeclarationForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            FormActions(Submit('save', "Soumettre la déclaration"))
        )

    # Meta
    class Meta:
        model = ManifestationDeclaration
        fields = ()


class DeclarationPublishReceiptForm(GenericForm):
    """ Formulaire de publication du récépissé de déclaration """

    def __init__(self, *args, **kwargs):
        """ Créer le layout du formulaire via crispy_forms """
        super(DeclarationPublishReceiptForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            Fieldset("Sélection du récépissé de déclaration", 'receipt'),
            FormActions(Submit('save', "Publier le récépissé de déclaration"))
        )

    # Validation
    def clean_receipt(self):
        data = self.cleaned_data['receipt']
        if not data:
            raise forms.ValidationError("Vous devez sélectionner un récépissé de déclaration")
        return data

    # Meta
    class Meta:
        model = ManifestationDeclaration
        fields = ['receipt']

declarations/templates/declarations/archives_mairieagent.html
{% extends "base.html" %}

{# load url from future #}
{% load i18n %}

{% block head_title %}
    Tableau de bord instructeur
{% endblock %}

{% block page_title %}
    <h1><i class="tableau-de-bord"></i> Tableau de bord des archives
        <a href="{% url 'declarations:dashboard' %}"><span class="pull-right label label-primary">&nbsp;<i class="retour"></i></span></a></h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h3><i class="autorisation"></i> Autorisations ou déclarations compétitives<br></h3>

            <div class="panel  authorizations-requested">
                <div class="list-group">
                    {% for authorization in autorisations %}
                        <a class="list-group-item
                            {% if authorization.state == 'published' %}
                                list-group-item-success
                            {% elif authorization.state == 'dispatched' %}
                                list-group-item-warning
                            {% elif authorization.state == 'created' %}
                                list-group-item-danger
                            {% endif %}
                            "
                           href="{% url 'authorizations:authorization_detail' authorization.id %}">{{ authorization.manifestation.begin_date|date:"d/m/Y" }} : {{ authorization.manifestation }}<br>
                           <small>↦ {{ authorization.manifestation.departure_city }}
                           {% if INSTANCE.get_instruction_mode %}
                                ({{ authorization.manifestation.departure_city.arrondissement }})
                            {% endif %}</small>

                            {% if not authorization.state == 'created' %}
                                {% if authorization.are_avis_validated %}
                                    <span class="badge badge-success top-right"><i class="ok"></i></span>
                                {% else %}
                                    <span class="badge badge-secondary top-right">{{ authorization.get_pending_avis_count }}&nbsp; avis manquants</span>
                                {% endif %}
                            {% endif %}
                        </a>
                    {% empty %}
                        <a class="list-group-item disabled">Aucune autorisation à gérer</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <h3><i class="declaration"></i> Déclarations</h3>

            <div class="panel  declarations">
                <div class="list-group">
                    {% for declaration in object_list %}
                        <a class="list-group-item
                            {% if declaration.state == 'published' %}
                                list-group-item-success
                            {% elif declaration.state == 'created' %}
                                list-group-item-danger
                            {% endif %}
                            "
                           href="{% url 'declarations:declaration_detail' declaration.id %}">{{ declaration.manifestation.begin_date|date:"d/m/Y" }}
                            : {{ declaration.manifestation }}<br>
                             <small>↦ {{ declaration.manifestation.departure_city }}
                           {% if INSTANCE.get_instruction_mode %}
                                ({{ declaration.manifestation.departure_city.arrondissement }})
                            {% endif %}</small>

                        </a>
                    {% empty %}
                        <a class="list-group-item disabled">Aucune déclaration à gérer</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

declarations/templates/declarations/dashboard_mairieagent.html
{% extends "base.html" %}

{# load url from future #}
{% load i18n %}

{% block head_title %}
    Tableau de bord instructeur
{% endblock %}

{% block page_title %}
    <h1><i class="tableau-de-bord"></i> Tableau de bord des instructions en mairie
        <a href="{% url 'declarations:archives' %}"><span class="float-right badge badge-primary attendre-archive"><i class="archive"></i>Archives</span></a>
<br>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h3><i class="autorisation"></i> Autorisations ou déclarations compétitives<br></h3>

            <div class="panel  authorizations-requested">
                <div class="list-group">
                    {% for authorization in autorisations %}
                        <a class="list-group-item
                            {% if authorization.state == 'published' %}
                                list-group-item-success
                            {% elif authorization.state == 'dispatched' %}
                                list-group-item-warning
                            {% elif authorization.state == 'created' %}
                                list-group-item-danger
                            {% endif %}
                            "
                           href="{% url 'authorizations:authorization_detail' authorization.id %}">{{ authorization.manifestation.begin_date|date:"d/m/Y" }} : {{ authorization.manifestation }}<br>
                            <small><i class="carto"></i> {{ authorization.manifestation.departure_city }}
                           {% if INSTANCE.get_instruction_mode %}
                                ({{ authorization.manifestation.departure_city.arrondissement }})
                            {% endif %}
                            <span class="pipe_separator"></span><i class="activite"></i> {{ authorization.manifestation.activite }}
                            </small>

                            {% if not authorization.state == 'created' %}
                                {% if authorization.are_avis_validated %}
                                    <span class="badge badge-success top-right"><i class="ok no-right-margin"></i></span>
                                {% else %}
                                    <span class="badge badge-secondary top-right">{{ authorization.get_pending_avis_count }}&nbsp; avis manquants</span>
                                {% endif %}
                            {% endif %}
                        </a>
                    {% empty %}
                        <a class="list-group-item disabled">Aucune autorisation à gérer</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <h3><i class="declaration"></i> Déclarations</h3>

            <div class="panel  declarations">
                <div class="list-group">
                    {% for declaration in object_list %}
                        <a class="list-group-item
                            {% if declaration.state == 'published' %}
                                list-group-item-success
                            {% elif declaration.state == 'created' %}
                                list-group-item-danger
                            {% endif %}
                            "
                           href="{% url 'declarations:declaration_detail' declaration.id %}">{{ declaration.manifestation.begin_date|date:"d/m/Y" }}
                            : {{ declaration.manifestation }}<br>
                            <small><i class="carto"></i> {{ declaration.manifestation.departure_city }}
                           {% if INSTANCE.get_instruction_mode %}
                                ({{ declaration.manifestation.departure_city.arrondissement }})
                            {% endif %}
                            <span class="pipe_separator"></span><i class="activite"></i> {{ declaration.manifestation.activite }}
                            </small>

                        </a>
                    {% empty %}
                        <a class="list-group-item disabled">Aucune déclaration à gérer</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
    <div class="col-sm-6">
        {% include "notifications/actions_list_decl.html" %}
    </div>
    <div class="col-sm-6">
        {% include "notifications/notifications_list_decl.html" %}
    </div>
    </div>
{% endblock %}

declarations/templates/declarations/manifestationdeclaration_detail.html
{% extends "base.html" %}


{% load i18n %}

{% block head_title %}
    Déclaration de Manifestation
{% endblock %}

{% block page_title %}
    <div class="row">
        <div class="col-sm-2">
            <i class="declaration"></i>Déclaration <br>
            <i class="date"></i> {{ object.manifestation.begin_date|date:"d/m/Y" }}
        </div>
        <div class="col-sm-7">
            <i class="structure"></i> {{ object.manifestation.structure|capfirst }}<br>
            <i class="dossier"></i> {{ object.manifestation|capfirst }}
        </div>
        <div class="col-sm-3 text-right">
            {% include 'events/event_picto.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-8">
            <ul class="nav nav-pills">
                <li class="nav-item"><a class="nav-link active" href="#declaration" data-toggle="pill"><i class="suivi"></i> Suivi de l'instruction</a></li>
                <li class="nav-item"><a class="nav-link" href="#event" data-toggle="pill"><i class="detail"></i> Détail de la manifestation</a></li>
                {% include 'events/event_tabs.html' with object=object.manifestation %}
            </ul>
            <div class="tab-content">
                <div id="declaration" class="card  tab-pane fade show active">
                    <ul class="list-group">
                        {% if object.manifestation.creation_date %}
                            <li class="list-group-item">Date de création du dossier : {{ object.manifestation.creation_date }}</li>
                      	{% endif %}
                        <li class="list-group-item">Date d'envoi de la déclaration : {{ object.creation_date }}</li>
                        {% if object.receipt %}
                            <li class="list-group-item">Récépissé de déclaration : <a href="{{ object.receipt.url }}" target='_blank'>{{ object.receipt }}</a></li>
                        {% endif %}
                    </ul>
                </div>
                {% include 'events/event_panel_instructor.html' with object=object.manifestation %}
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-header bg-primary">
                    <i class="action"></i> Actions disponibles
                </div>
                <div class="card-body">
                    <p>Veuillez trouver ici toutes les actions disponibles pour cette manifestation</p>
                <ul class="list-no-style">
                    {% if object.state != 'published' %}
                        <li>
                            <a href="{% url 'events:additional_data_add' manifestation_pk=object.manifestation.id %}" class="btn" role="button">
                                <i class="ajouter"></i> Demander plus d'informations
                            </a>
                        </li>
                    {% endif %}
                    {% if object.state == 'created' %}
                        <li>
                            <a href="{% url 'declarations:declaration_publish' pk=object.id %}" class="btn" role="button">
                                <i class="recepisse"></i> Publier le récépissé de déclaration
                            </a>
                        </li>
                    {% endif %}
                </ul>
                </div>
            </div>
            {% if user.instructeur %}
                <a href="{% url 'declarations:dashboard' %}" class="btn btn-outline-secondary btn-fill mt-4" role="button"><i class="retour"></i>
                    Tableau de bord des instructions en mairie<i class="tableau-de-bord left-margin"></i></a>
                <a href="{% url 'authorizations:dashboard' %}" class="btn btn-outline-secondary btn-fill mt-3" role="button"><i class="retour"></i>
                    Revenir au tableau de bord <i class="tableau-de-bord left-margin"></i></a>
            {% elif user.agent.mairieagent %}
                <a href="{% url 'declarations:dashboard' %}" class="btn btn-outline-secondary btn-fill mt-4" role="button"><i class="retour"></i>
                    Revenir au tableau de bord <i class="tableau-de-bord left-margin"></i></a>
            {% else %}
                <a href="{% url 'events:dashboard' %}" class="btn btn-outline-secondary btn-fill mt-3" role="button"><i class="retour"></i>
                    Revenir au tableau de bord <i class="tableau-de-bord left-margin"></i></a>
            {% endif %}
        </div>
    </div>
{% endblock %}

declarations/templates/declarations/manifestationdeclaration_form.html
{% extends "base_form.html" %}

{% load i18n %}

{% block head_title %}
    Déclaration de manifestation
{% endblock %}

{% block page_title %}
    <h1><i class="declaration"></i> Déclaration de manifestation : {{ object.manifestation|capfirst }}</h1>
{% endblock %}

declarations/templates/declarations/manifestationdeclaration_publish_form.html
{% extends "base_form.html" %}

{% load i18n %}

{% block head_title %}
    Publication du récépissé de déclaration
{% endblock %}

{% block page_title %}
    <h1>Publication du récépissé de déclaration pour la manifestation : {{ object.manifestation|capfirst }}</h1>
{% endblock %}