aide/urls.py
# coding: utf-8
from django.urls import path, re_path

from aide import views


app_name = 'aide'
urlpatterns = [
    # Aide : sommaire
    path('', views.view_help_page, {"path": "sommaire"}, name="help-sommaire"),

    # Aide : liste
    path('liste', views.view_help_list, name="help-list"),

    # Aide contextuelle
    re_path('context/(?P<name>.+)', views.view_context_help, name="context"),

    # formulaire de demande
    path('contact', views.demande, name="contact"),

    # Aide : page
    re_path('(?P<path>[a-zA-Z0-9-/_]+)/(?P<pk>\d+)', views.view_help_page, name="help-accordion-page-direct"),
    re_path('(?P<path>.+)', views.view_help_page, name="help-page"),
]

api/urls.py
from django.urls import include, path
from api.views.organisateur import OrganisateurViewSet
from api.views.manifestation import ManifestationAutorisationViewSet, ManifestationDeclarationViewSet
from api.views.manif import InstructionViewSet
from rest_framework import routers


app_name = 'api'
router = routers.DefaultRouter()
# router.register(r'manifestations', api_views.ManifestationAllViewSet)
router.register(r'Instruction', InstructionViewSet, basename='Instruction')
router.register(r'ManifestationAutorisation', ManifestationAutorisationViewSet, basename='ManifestationAutorisation')
router.register(r'ManifestationDeclaration', ManifestationDeclarationViewSet, basename='ManifestationDeclaration')
router.register(r'Organisateur', OrganisateurViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

configuration/urls.py
import debug_toolbar
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.http import HttpResponseBadRequest

from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap

from core.views.ajax import validate_form
from core.views.user import (ProfileDetailView, UserUpdateView, signupagentview, signuporganisateurview,
                             EmailConfirmedView, NomPrenomChange, PasswordExpired, PasswordChangeCustomView, RenvoiMailConfirm)
from core.views.media import media_access
from organisateurs.views import StructureUpdateView
from portail.views.index import HomePage

# Todo : à supprimer après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
from aide import views

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}
handler400 = 'portail.views.erreur400view'
handler403 = 'portail.views.erreur403view'
handler404 = 'portail.views.erreur404view'
handler500 = 'portail.views.erreur500view'

urlpatterns = [
    # Examples:
    # path('', 'ddcs_loire.views.home', name='home'),
    # path('blog/', include('blog.urls')),

    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap\.xml', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    path('accounts/signup/', HttpResponseBadRequest),
    path('accounts/password/change/', PasswordChangeCustomView.as_view(), name='password_change_custom'),
    path('accounts/', include('allauth.urls')),
    path('accounts/passwordexpired', PasswordExpired.as_view(), name="password_expired"),
    path('accounts/send_confirm_mail/<int:pk>/', RenvoiMailConfirm.as_view(), name="send_confirm_mail"),
    path('accounts/email_confirmed', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('accounts/profile/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile/edit', UserUpdateView.as_view(), name='profile_edit'),
    path('accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    path('accounts/profilte/name', NomPrenomChange.as_view(), name="nom_prenom_change"),
    path('inscription/agent', signupagentview, name='inscription_agent'),
    path('inscription/organisateur', signuporganisateurview, name='inscription_organisateur'),
    path('administration/', include('administration.urls')),
    path('agreements/', include('agreements.urls')),
    path('carto/', include('carto.urls')),
    path('sub_agreements/', include('sub_agreements.urls')),
    path('instructions/', include('instructions.urls')),
    path('authorizations/', include('authorizations.urls')),
    path('declarations/', include('declarations.urls')),
    path('evaluations/', include('evaluations.urls')),
    path('incidence/', include('evaluation_incidence.urls')),
    path('notifications/', include('notifications.urls')),
    path('nouveautes/', include('nouveautes.urls')),
    path('sports/', include('sports.urls')),
    path('administrative_division/', include('administrative_division.urls')),
    path('', include('events.urls')),
    path('', include('evenements.urls')),
    path('protected_areas/', include('protected_areas.urls')),
    re_path('validate/(?P<alias>[\w\-]+)/', validate_form, name='validate'),
    path('ajax_select/', include('ajax_select.urls')),
    path('', include('portail.urls')),
    path('', HomePage.as_view(), name='home_page'),
    path('aide/', include('aide.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    # Todo : à réactiver après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
    # Todo : à supprimer après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
    #re_path('(?P<path>.+)', views.view_help_page, name="help-page"),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)', media_access, name='media'),

# Les flatpages doivent être toujours après les média pour eviter une interceptions des demandes de media
urlpatterns += path('', include('django.contrib.flatpages.urls')),

portail/urls.py
# coding: utf-8
from django.urls import path, re_path

from .views.calendar import Calendar
from .views.index import HomePage
from .views.stat import Stat
from .views.stat_instructeur import StatInstructeur


app_name = 'portail'
urlpatterns = [

    # Accueil
    path('', HomePage.as_view(), name='home_page'),

    # Calendrier
    re_path('calendar/(?P<activite>\d+)/', Calendar.as_view(), name="filtered_calendar"),
    path('calendar/', Calendar.as_view(), name="calendar"),
    path('stat/', Stat.as_view(), name="stat"),
    path('stat_instructeur/', StatInstructeur.as_view(), name="stat_instructeur"),
]

portail/forms.py
from django.forms import Form, DateField
from bootstrap_datepicker_plus import DatePickerInput


class CalendrierForm(Form):
    # Formulaire qui permet de générer un input date avec bootstrap_datepicker_plus
    date = DateField(widget=DatePickerInput(format='%d/%m/%Y', options={'locale': 'fr'}))

portail/views/calendar.py
# coding: utf-8
from django.db.models import Subquery
from django.views.generic import ListView

from events.forms import *
from events.models import *
from sports.models import Activite
from evenements.models import Manif
from portail.forms import CalendrierForm


class Calendar(ListView):
    """ Calendrier des manifestations """

    # Configuration
    model = Manifestation
    template_name = 'portail/calendar.html'

    # Overrides
    def get_queryset(self):
        now = timezone.now()
        instance = Instance.objects.get_for_request(self.request)
        departement = instance.get_departement()
        activite = self.kwargs.get('activite')
        filtre_activite = Q(activite=activite) if activite else Q()
        param_dep = self.request.GET.get('dep', None)
        param_com = self.request.GET.get('com', '0')
        if param_dep:
            if not param_dep.isdecimal():
                departement = None
            else:
                departement = Departement.objects.filter(pk=param_dep)
                departement = departement.get() if departement else None
        resultat = Manif.objects.filter(date_debut__gt=now, prive=False, cache=False).filter(
            Q(instruction__id__isnull=False) | Q(instance_id__isnull=True)
        ).exclude(instruction__etat__in=['interdite', 'annulée']).filter(filtre_activite)
        # Afficher les manifs du département, ou toute sur le domaine master
        if departement is not None:
            resultat = resultat.filter(ville_depart__arrondissement__departement=departement)
        if param_com != '0':
            resultat = resultat.filter(ville_depart__pk=param_com)

        return resultat.order_by('date_debut')

    def get_context_data(self, **kwargs):
        now = timezone.now()
        instance = Instance.objects.get_for_request(self.request)
        departement = instance.get_departement()
        context = super(Calendar, self).get_context_data(**kwargs)
        param_dep = self.request.GET.get('dep', None)
        param_com = self.request.GET.get('com', '0')
        liste_activite = Activite.objects.filter(
            Q(manifs__instruction__id__isnull=False) | Q(manifs__instance_id__isnull=True),
            ~Q(manifs__instruction__etat__in=['interdite', 'annulée']),
            manifs__date_debut__gt=now, manifs__cache=False, manifs__prive=False)
        if param_dep:
            if not param_dep.isdecimal():
                departement = None
            else:
                departement = Departement.objects.filter(pk=self.request.GET['dep'])
                departement = departement.get() if departement else None
                if departement:
                    liste_activite = Activite.objects.filter(
                        Q(manifs__instruction__id__isnull=False) | Q(manifs__instance_id__isnull=True),
                        ~Q(manifs__instruction__etat__in=['interdite', 'annulée']),
                        manifs__date_debut__gt=now, manifs__cache=False, manifs__prive=False,
                        manifs__ville_depart__arrondissement__departement=departement)
        else:
            liste_activite = Activite.objects.filter(
                Q(manifs__instruction__id__isnull=False) | Q(manifs__instance_id__isnull=True),
                ~Q(manifs__instruction__etat__in=['interdite', 'annulée']),
                manifs__date_debut__gt=now, manifs__cache=False, manifs__prive=False,
                manifs__ville_depart__arrondissement__departement=departement)

        context['dep_actuel'] = departement
        context['com_actuel'] = int(param_com)
        context['activities'] = liste_activite.distinct('name').order_by('name')
        context['current_activite'] = int(self.kwargs.get('activite')) if self.kwargs.get('activite') else None
        context['dep'] = Departement.objects.filter(pk__in=Subquery(
            Manif.objects.all().values('ville_depart__arrondissement__departement__pk')))
        context['comm'] = Commune.objects.filter(arrondissement__departement=departement)
        context['form'] = CalendrierForm()
        return context

portail/views/index.py
# coding: utf-8
from django.views.generic.base import TemplateView
from django.shortcuts import render

from core.models.instance import Instance


class HomePage(TemplateView):
    """ Page d'accueil """

    # Configuration
    template_name = 'portail/index.html'

    # Méthodes
    def get_context_data(self, **kwargs):
        """ Définir le contexte d'affichage de la page """
        context = super(HomePage, self).get_context_data(**kwargs)
        instance = Instance.objects.get_for_request(self.request)
        context['INSTANCES'] = Instance.objects.configured()
        context['IS_MASTER'] = instance.is_master()
        # Domaine sans instance : ne pas afficher le calendrier
        context['HIDE_CALENDAR'] = instance.is_master()
        return context


def erreur400view(request, exception):
    return render(request,'400.html', {'message': exception}, status=400)


def erreur403view(request, exception):
    return render(request,'403.html', {'message': exception}, status=403)


def erreur404view(request, exception):
    return render(request,'404.html', {'message': exception}, status=404)


def erreur500view(request):
    return render(request,'500.html', status=500)

portail/templates/portail/index.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}


{% block head_title %} Manifestations Sportives | Plateforme {{ INSTANCE.get_departement_friendly_name }}
{% endblock %}

{% block custom_head %}
    <link href="{% static 'portail/css/index.css' %}" rel='stylesheet' type='text/css'>
{% endblock %}

{% block body %}
    {% block content %}
        {# Le commentaire HTML ci-dessous doit être conservé !! #}
        <!-- Sous-domaine {{ INSTANCE.name }} -->

        <!-- bof #carrousel -->
        <div id="carrousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carrousel" data-slide-to="0" class="active"></li>
                <li data-target="#carrousel" data-slide-to="1"></li>
                <li data-target="#carrousel" data-slide-to="2"></li>
                <li data-target="#carrousel" data-slide-to="3"></li>
                <li data-target="#carrousel" data-slide-to="4"></li>
                <li data-target="#carrousel" data-slide-to="5"></li>
                <li data-target="#carrousel" data-slide-to="6"></li>
                <li data-target="#carrousel" data-slide-to="7"></li>
                <li data-target="#carrousel" data-slide-to="8"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img alt="slide" src="{% static 'portail/img/carousel01.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel02.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel03.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel04.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel05.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel06.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel07.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel08.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                    </div>
                </div>
                <div class="carousel-item">
                    <img alt="slide" src="{% static 'portail/img/carousel09.jpg' %}">
                    <div class="carousel-caption">
                        <span class="carousel-caption-text">Démarches en ligne de déclarations et autorisation d'évènements sportifs</span>
                    </div>
                </div>
            </div>
            <!-- Controls -->
            <a class="left carousel-control-prev" href="#carrousel" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            </a>
            <a class="right carousel-control-next" href="#carrousel" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
            </a>
        </div>
        <!-- eof #carrousel -->

        <!-- bof contenu -->
        <div class='container'>
        <div class="row" style="background-color: #015A70;">

            <!-- bof 1e colonne -->
            <div class="col-md-4 background-contrast">

                <div id="carte-fr"></div>

                <script type="text/javascript">
                    var instances = {};
                    {% for instance in INSTANCES %}
                        // Todo : à réactiver après la mise en place d'un certificat avec tous les sous-domaines sachant qu'il y a une erreur avec request.META.SERVER_NAME
                        // instances["FR-{{ instance.get_departement.name }}"] = "{{ request.is_secure|yesno:"https,http" }}://{{ instance.get_departement.name }}.{{ request.META.SERVER_NAME }}:{{ request.META.SERVER_PORT }}";
                        instances["FR-{{ instance.get_departement.name }}"] = "http://{{ instance.get_departement.name }}.manifestationsportive.fr";
                    {% endfor %}
                </script>

            </div>
            <!-- eof 1e colonne -->

            <!-- bof 2e colonne -->
            <div class="col-md-8">

                <!-- bof ligne de titre -->
                <div class="row background-contrast">
                    <div class="col-md-6">

                        <div class="cadre-blanc">
                            <h1 class="text-center h1-home">
                                MANIFESTATIONS SPORTIVES<br/>
                                <strong>PLATEFORME {{ INSTANCE.get_departement_name }}</strong>
                            </h1>
                        </div>

                    </div>
                    <div class="col-md-6 d-none d-md-block">

                        <div class="cadre-blanc cadre-rf">
                            <img alt="Logo République Française"
                                 src="{% static 'portail/img/Logo_de_la_Republique_francaise_102x60.png' %}">
                            <span class="cadre-rf-text">Ministère des Sports</span>
                        </div>

                    </div>
                </div>
                <!-- eof ligne de titre -->

                <!-- bof ligne de boutons dynamiques -->
                <div class="row">
                    <div class="col-lg button-home">
                    {% if not IS_MASTER %}
                        <a href="{% url 'portail:calendar' %}" class="btn btn-block" role="button">
                            <i class="date"></i>
                            <h2 class="text-center h2-home">Calendrier</h2>
                            <span class="">Les manifestations sportives sur le département</span>
                        </a>
                    {%  else %}
                        <a href="{% url 'portail:calendar' %}?dep=master" class="btn btn-block" role="button">
                            <i class="date"></i>
                            <h2 class="text-center h2-home">Calendrier</h2>
                            <span class="">Les manifestations sportives dans chaque département</span>
                        </a>
                    {% endif %}
                    </div>
                {% if not user.is_authenticated %}
                    <div class="col-lg  button-home">
                        <a href="{% url 'inscription_organisateur' %}" class="btn btn-block" role="button">
                            <i class="sincrire"></i>
                            <h2 class="text-center h2-home">Inscription</h2>
                            <span class="">Organisateurs d'évenements sportifs, inscrivez-vous !</span>
                        </a>
                    </div>
                {% endif %}
                    <div class="col-lg button-home">
                        <a href="{% url "aide:help-page" path="sommaire" %}" class="btn btn-block" role="button">
                            <i class="aide"></i>
                            <h2 class="text-center h2-home">Aide & infos</h2>
                            <span class="text-center">Espace dédié aux organisateurs, fédérations et services instructeurs</span>
                        </a>
                    </div>
                </div>
                <!-- bof ligne de boutons dynamiques -->

            </div>
            <!-- bof 2e colonne -->

        </div>
        </div>
        <!-- bof contenu -->


    <script src="{% static 'portail/js/homepage.js' %}" type="text/javascript"></script>

    {% endblock %}
{% endblock %}