api/urls.py
from django.urls import include, path
from api.views.organisateur import OrganisateurViewSet
from api.views.manifestation import ManifestationAutorisationViewSet, ManifestationDeclarationViewSet
from api.views.manif import InstructionViewSet
from rest_framework import routers


app_name = 'api'
router = routers.DefaultRouter()
# router.register(r'manifestations', api_views.ManifestationAllViewSet)
router.register(r'Instruction', InstructionViewSet, basename='Instruction')
router.register(r'ManifestationAutorisation', ManifestationAutorisationViewSet, basename='ManifestationAutorisation')
router.register(r'ManifestationDeclaration', ManifestationDeclarationViewSet, basename='ManifestationDeclaration')
router.register(r'Organisateur', OrganisateurViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

configuration/urls.py
import debug_toolbar
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.http import HttpResponseBadRequest

from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap

from core.views.ajax import validate_form
from core.views.user import (ProfileDetailView, UserUpdateView, signupagentview, signuporganisateurview,
                             EmailConfirmedView, NomPrenomChange, PasswordExpired, PasswordChangeCustomView, RenvoiMailConfirm)
from core.views.media import media_access
from organisateurs.views import StructureUpdateView
from portail.views.index import HomePage

# Todo : à supprimer après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
from aide import views

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}
handler400 = 'portail.views.erreur400view'
handler403 = 'portail.views.erreur403view'
handler404 = 'portail.views.erreur404view'
handler500 = 'portail.views.erreur500view'

urlpatterns = [
    # Examples:
    # path('', 'ddcs_loire.views.home', name='home'),
    # path('blog/', include('blog.urls')),

    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap\.xml', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    path('accounts/signup/', HttpResponseBadRequest),
    path('accounts/password/change/', PasswordChangeCustomView.as_view(), name='password_change_custom'),
    path('accounts/', include('allauth.urls')),
    path('accounts/passwordexpired', PasswordExpired.as_view(), name="password_expired"),
    path('accounts/send_confirm_mail/<int:pk>/', RenvoiMailConfirm.as_view(), name="send_confirm_mail"),
    path('accounts/email_confirmed', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('accounts/profile/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile/edit', UserUpdateView.as_view(), name='profile_edit'),
    path('accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    path('accounts/profilte/name', NomPrenomChange.as_view(), name="nom_prenom_change"),
    path('inscription/agent', signupagentview, name='inscription_agent'),
    path('inscription/organisateur', signuporganisateurview, name='inscription_organisateur'),
    path('administration/', include('administration.urls')),
    path('agreements/', include('agreements.urls')),
    path('carto/', include('carto.urls')),
    path('sub_agreements/', include('sub_agreements.urls')),
    path('instructions/', include('instructions.urls')),
    path('authorizations/', include('authorizations.urls')),
    path('declarations/', include('declarations.urls')),
    path('evaluations/', include('evaluations.urls')),
    path('incidence/', include('evaluation_incidence.urls')),
    path('notifications/', include('notifications.urls')),
    path('nouveautes/', include('nouveautes.urls')),
    path('sports/', include('sports.urls')),
    path('administrative_division/', include('administrative_division.urls')),
    path('', include('events.urls')),
    path('', include('evenements.urls')),
    path('protected_areas/', include('protected_areas.urls')),
    re_path('validate/(?P<alias>[\w\-]+)/', validate_form, name='validate'),
    path('ajax_select/', include('ajax_select.urls')),
    path('', include('portail.urls')),
    path('', HomePage.as_view(), name='home_page'),
    path('aide/', include('aide.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    # Todo : à réactiver après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
    # Todo : à supprimer après réécriture de la documentation (renvoi de l'ancienne doc vers aide/help_page)
    #re_path('(?P<path>.+)', views.view_help_page, name="help-page"),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)', media_access, name='media'),

# Les flatpages doivent être toujours après les média pour eviter une interceptions des demandes de media
urlpatterns += path('', include('django.contrib.flatpages.urls')),

evenements/urls.py
# coding: utf-8
from django.urls import path, re_path

from .views.dnm import DnmCreate, DnmDetail, DnmUpdate, DnmFilesUpdate, DnmDelete
from .views.dcnm import DcnmCreate, DcnmDetail, DcnmUpdate, DcnmFilesUpdate, DcnmDelete
from .views.dnmc import DnmcCreate, DnmcDetail, DnmcUpdate, DnmcFilesUpdate, DnmcDelete
from .views.dcnmc import DcnmcCreate, DcnmcDetail, DcnmcUpdate, DcnmcFilesUpdate, DcnmcDelete
from .views.dvtm import DvtmCreate, DvtmDetail, DvtmUpdate, DvtmFilesUpdate, DvtmDelete
from .views.avtm import AvtmCreate, AvtmDetail, AvtmUpdate, AvtmFilesUpdate, AvtmDelete
from .views.avtmcir import AvtmcirCreate, AvtmcirDetail, AvtmcirUpdate, AvtmcirFilesUpdate, AvtmcirDelete
from .views.dashboard import TableauDeBordOrganisateur
from .views.manif import ManifInstructeurUpdate, ManifPublicDetail, ManifCartoUpdate, ManifCreateAncien, ManifUrlGen
from .views.documentcomplementaire import (
    DocumentComplementaireProvideView,
    DocumentComplementaireRequestView,
    EnvoiDocumentComplementaire,
)
from .views.sansinstance import SansInstanceManifCreate
from .views.create import CreationEvenementView
from .views.exportation import ExportPourInstructeur, ExportPourOrganisateur, ExportPourAgentlocal, ExportPourAgent


app_name = 'evenements'
urlpatterns = [

    # Tableau de bord principal
    path('tableau-de-bord-organisateur/', TableauDeBordOrganisateur.as_view(), name="tableau-de-bord-organisateur"),

    path('evenement/creation/', CreationEvenementView.as_view(), name='creation_evenement'),
    path('evenement/creationancien/', ManifCreateAncien.as_view(), name='creation_ancien'),

    # Manifestation sans type (non supporté)
    path('sansinstance/add/', SansInstanceManifCreate.as_view(), name="manif_sansinstance_add"),

    # Modifications instructeur
    re_path('evenement/(?P<pk>\d+)/instruction/', ManifInstructeurUpdate.as_view(), name="manifestation_instructeur"),
    re_path('evenement/(?P<pk>\d+)/cartoedit/', ManifCartoUpdate.as_view(), name="manif_carto"),
    re_path('evenement/(?P<manif_pk>\d+)/doc_complementaire/add/', DocumentComplementaireRequestView.as_view(), name="demander_doc_complementaire"),

    path('evenement/<int:pk>/export/instructeur/', ExportPourInstructeur.as_view(), name="export_manif_instructeur"),
    path('evenement/<int:pk>/export/organisateur/', ExportPourOrganisateur.as_view(), name="export_manif_organisateur"),
    path('evenement/<int:pk>/export/agent/', ExportPourAgent.as_view(), name="export_manif_agent"),
    path('evenement/<int:pk>/export/agentlocal/', ExportPourAgentlocal.as_view(), name="export_manif_agentlocal"),

    path('doc_complementaire/<int:pk>/repondre/', EnvoiDocumentComplementaire.as_view(), name='repondre_doc_complementaire'),
    re_path('doc_complementaire/(?P<pk>\d+)/', DocumentComplementaireProvideView.as_view(), name="fournir_doc_complementaire"),
    path('doc_complementaire/new/<int:pk>', EnvoiDocumentComplementaire.as_view(), name='fournir_doc_complementaire_new'),
    re_path('evenement/(?P<pk>\d+)/', ManifPublicDetail.as_view(), name="manif_detail"),
    re_path('manifestation/(?P<pk>\d+)/', ManifUrlGen.as_view(), name="manif_url"),

    # Dnm urls
    path('Dnm/add/', DnmCreate.as_view(), name="dnm_add"),
    re_path('Dnm/(?P<pk>\d+)/edit/', DnmUpdate.as_view(), name="dnm_update"),
    re_path('Dnm/(?P<pk>\d+)/edit_files/', DnmFilesUpdate.as_view(), name="dnm_files_update"),
    re_path('Dnm/(?P<pk>\d+)/delete/', DnmDelete.as_view(), name="dnm_delete"),
    re_path('Dnm/(?P<pk>\d+)/', DnmDetail.as_view(), name="dnm_detail"),

    # Dnmc urls
    path('Dnmc/add/', DnmcCreate.as_view(), name="dnmc_add"),
    re_path('Dnmc/(?P<pk>\d+)/edit/', DnmcUpdate.as_view(), name="dnmc_update"),
    re_path('Dnmc/(?P<pk>\d+)/edit_files/', DnmcFilesUpdate.as_view(), name="dnmc_files_update"),
    re_path('Dnmc/(?P<pk>\d+)/delete/', DnmcDelete.as_view(), name="dnmc_delete"),
    re_path('Dnmc/(?P<pk>\d+)/', DnmcDetail.as_view(), name="dnmc_detail"),

    # Dcnm urls
    path('Dcnm/add/', DcnmCreate.as_view(), name="dcnm_add"),
    re_path('Dcnm/(?P<pk>\d+)/edit/', DcnmUpdate.as_view(), name="dcnm_update"),
    re_path('Dcnm/(?P<pk>\d+)/edit_files/', DcnmFilesUpdate.as_view(), name="dcnm_files_update"),
    re_path('Dcnm/(?P<pk>\d+)/delete/', DcnmDelete.as_view(), name="dcnm_delete"),
    re_path('Dcnm/(?P<pk>\d+)/', DcnmDetail.as_view(), name="dcnm_detail"),

    # Dcnmc urls
    path('Dcnmc/add/', DcnmcCreate.as_view(), name="dcnmc_add"),
    re_path('Dcnmc/(?P<pk>\d+)/edit/', DcnmcUpdate.as_view(), name="dcnmc_update"),
    re_path('Dcnmc/(?P<pk>\d+)/edit_files/', DcnmcFilesUpdate.as_view(), name="dcnmc_files_update"),
    re_path('Dcnmc/(?P<pk>\d+)/delete/', DcnmcDelete.as_view(), name="dcnmc_delete"),
    re_path('Dcnmc/(?P<pk>\d+)/', DcnmcDetail.as_view(), name="dcnmc_detail"),

    # Dvtm urls
    path('Dvtm/add/', DvtmCreate.as_view(), name="dvtm_add"),
    re_path('Dvtm/(?P<pk>\d+)/edit/', DvtmUpdate.as_view(), name="dvtm_update"),
    re_path('Dvtm/(?P<pk>\d+)/edit_files/', DvtmFilesUpdate.as_view(), name="dvtm_files_update"),
    re_path('Dvtm/(?P<pk>\d+)/delete/', DvtmDelete.as_view(), name="dvtm_delete"),
    re_path('Dvtm/(?P<pk>\d+)/', DvtmDetail.as_view(), name="dvtm_detail"),

    # Avtm urls
    path('Avtm/add/', AvtmCreate.as_view(), name="avtm_add"),
    re_path('Avtm/(?P<pk>\d+)/edit/', AvtmUpdate.as_view(), name="avtm_update"),
    re_path('Avtm/(?P<pk>\d+)/edit_files/', AvtmFilesUpdate.as_view(), name="avtm_files_update"),
    re_path('Avtm/(?P<pk>\d+)/delete/', AvtmDelete.as_view(), name="avtm_delete"),
    re_path('Avtm/(?P<pk>\d+)/', AvtmDetail.as_view(), name="avtm_detail"),

    # Avtmcir urls
    path('Avtmcir/add/', AvtmcirCreate.as_view(), name="avtmcir_add"),
    re_path('Avtmcir/(?P<pk>\d+)/edit/', AvtmcirUpdate.as_view(), name="avtmcir_update"),
    re_path('Avtmcir/(?P<pk>\d+)/edit_files/', AvtmcirFilesUpdate.as_view(), name="avtmcir_files_update"),
    re_path('Avtmcir/(?P<pk>\d+)/delete/', AvtmcirDelete.as_view(), name="avtmcir_delete"),
    re_path('Avtmcir/(?P<pk>\d+)/', AvtmcirDetail.as_view(), name="avtmcir_detail"),

]

events/urls.py
# coding: utf-8
from django.urls import path, re_path

from events.views.autorisationnm import AutorisationNMFilesUpdate
from events.views.declarationnm import DeclarationNMFilesUpdate
from events.views.motorizedconcentration import MotorizedConcentrationFilesUpdate
from events.views.motorizedmanifestation import MotorizedEventFilesUpdate
from events.views.motorizedrace import MotorizedRaceFilesUpdate
from .views import ManifestationStartChoose
from .views import Dashboard
from .views import UnsupportedManifestationCreate
from .views import ManifestationInstructeurUpdate
from .views import AutorisationNMCreate
from .views import AutorisationNMDetail
from .views import AutorisationNMUpdate
from .views import CreateRoute
from .views import DeclarationNMChoose
from .views import DeclarationNMCreate
from .views import DeclarationNMDetail
from .views import DeclarationNMUpdate
from .views import DocumentComplementaireProvideView
from .views import DocumentComplementaireRequestView
from .views import MailToOrganisateursView
from .views import MailToTownHallsView
from .views import ManifestationChoose
from .views import ManifestationPublicDetail
from .views import MotorizedConcentrationCreate
from .views import MotorizedConcentrationDetail
from .views import MotorizedConcentrationUpdate
from .views import MotorizedEventChoose
from .views import MotorizedEventCreate
from .views import MotorizedEventDetail
from .views import MotorizedEventUpdate
from .views import MotorizedRaceCreate
from .views import MotorizedRaceDetail
from .views import MotorizedRaceUpdate
from .views import NonMotorizedEventChoose
from .views import PublicRoadMotorizedEventChoose
from organisateurs.views import StructureCreate


app_name = 'events'
urlpatterns = [

    # Tableau de bord principal
    path('dashboard/', Dashboard.as_view(), name="dashboard"),

    path('mail_to_promoters/', MailToOrganisateursView.as_view(), name='mail_to_promoters'),
    path('mail_to_townhalls/', MailToTownHallsView.as_view(), name='mail_to_townhalls'),
    path('structure/add', StructureCreate.as_view(), name='structure_add'),

    path('events/choose_start/', ManifestationStartChoose.as_view(), name='manifestation_start_choose'),
    path('events/create_route/', CreateRoute.as_view(), name='create_route'),
    path('events/choose/', ManifestationChoose.as_view(), name='manifestation_choose'),
    path('motorizedevents/choose', MotorizedEventChoose.as_view(), name="motorizedevent_choose"),
    path('nonmotorizedevents/choose', NonMotorizedEventChoose.as_view(), name="nonmotorizedevent_choose"),
    path('DeclarationNM/choose', DeclarationNMChoose.as_view(), name="declarationnm_choose"),
    path('publicroadmotorizedevents/choose', PublicRoadMotorizedEventChoose.as_view(), name="publicroadmotorizedevent_choose"),

    # Manifestation sans type (non supporté)
    path('unsupported/add/', UnsupportedManifestationCreate.as_view(), name="unsupported_manifestation_add"),

    # Modifications instructeur
    re_path('event/(?P<pk>\d+)/instruction/', ManifestationInstructeurUpdate.as_view(), name="manifestation_instructeur"),
    re_path('event/(?P<manifestation_pk>\d+)/additional_data/add', DocumentComplementaireRequestView.as_view(), name="additional_data_add"),
    re_path('event/(?P<pk>\d+)/', ManifestationPublicDetail.as_view(), name="manifestation_detail"),

    # DeclarationNM urls
    path('DeclarationNM/add/', DeclarationNMCreate.as_view(), name="declarationnm_add"),
    re_path('DeclarationNM/(?P<pk>\d+)/edit/', DeclarationNMUpdate.as_view(), name="declarationnm_update"),
    re_path('DeclarationNM/(?P<pk>\d+)/edit_files/', DeclarationNMFilesUpdate.as_view(), name="declarationnm_files_update"),
    re_path('DeclarationNM/(?P<pk>\d+)/', DeclarationNMDetail.as_view(), name="declarationnm_detail"),

    # AutorisationNM urls
    path('AutorisationNM/add/', AutorisationNMCreate.as_view(), name="autorisationnm_add"),
    re_path('AutorisationNM/(?P<pk>\d+)/edit/', AutorisationNMUpdate.as_view(), name="autorisationnm_update"),
    re_path('AutorisationNM/(?P<pk>\d+)/edit_files/', AutorisationNMFilesUpdate.as_view(), name="autorisationnm_files_update"),
    re_path('AutorisationNM/(?P<pk>\d+)/', AutorisationNMDetail.as_view(), name="autorisationnm_detail"),

    # MotorizedConcentration urls
    path('motorizedconcentrations/add/', MotorizedConcentrationCreate.as_view(), name="motorizedconcentration_add"),
    re_path('motorizedconcentrations/(?P<pk>\d+)/edit/', MotorizedConcentrationUpdate.as_view(), name="motorizedconcentration_update"),
    re_path('motorizedconcentrations/(?P<pk>\d+)/edit_files/', MotorizedConcentrationFilesUpdate.as_view(), name="motorizedconcentration_files_update"),
    re_path('motorizedconcentrations/(?P<pk>\d+)/', MotorizedConcentrationDetail.as_view(), name="motorizedconcentration_detail"),

    # MotorizedEvent urls
    path('motorizedevents/add/', MotorizedEventCreate.as_view(), name="motorizedevent_add"),
    re_path('motorizedevents/(?P<pk>\d+)/edit/', MotorizedEventUpdate.as_view(), name="motorizedevent_update"),
    re_path('motorizedevents/(?P<pk>\d+)/edit_files/', MotorizedEventFilesUpdate.as_view(), name="motorizedevent_files_update"),
    re_path('motorizedevents/(?P<pk>\d+)/', MotorizedEventDetail.as_view(), name="motorizedevent_detail"),

    # MotorizedRace urls
    path('motorizedraces/add/', MotorizedRaceCreate.as_view(), name="motorizedrace_add"),
    re_path('motorizedraces/(?P<pk>\d+)/edit/', MotorizedRaceUpdate.as_view(), name="motorizedrace_update"),
    re_path('motorizedraces/(?P<pk>\d+)/edit_files/', MotorizedRaceFilesUpdate.as_view(), name="motorizedrace_files_update"),
    re_path('additional_data/(?P<pk>\d+)/', DocumentComplementaireProvideView.as_view(), name="additional_data_provide"),
    re_path('motorizedraces/(?P<pk>\d+)/', MotorizedRaceDetail.as_view(), name="motorizedrace_detail"),

]

evenements/templates/evenements/dashboard_organisateur.html
{% extends "base.html" %}
{% load static %}

{% load i18n l10n %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'libs/DataTables/css/jquery.dataTables.css' %}">
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" charset="utf8" src="{% static 'libs/DataTables/js/jquery.dataTables.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="{% static 'libs/DataTables/js/datetime-moment.js' %}"></script>
{% endblock %}

{% block head_title %}
    Tableau de bord
{% endblock %}

{% block page_title %}
    <h1><i class="tableau-de-bord left-margin"></i> Tableau de bord organisateur
            <a href="{% url 'events:dashboard' %}">
                    <span class="float-right btn btn-primary btn-sm" style=" margin-right: 15px;"><i class="historique"></i>Ancienne réglementation</span></a>
    </h1>
{% endblock %}

{% block content %}
    {% if request.user.organisateur.structure %}
        <p><a href="{% url 'evenements:creation_evenement' %}" class="btn btn-primary" role="button">
            <i class="ajouter"></i> Déclarer ou demander l'autorisation pour une nouvelle manifestation
        </a></p>
        <div class="card card-primary">
            <div class="card-header">
                <h2><i class="dossier"></i> Mes manifestations   <i class="ctx-help-mes_manifestations fas fa-info-circle"></i>
                <input class="form-control float-right w-25" id="search" placeholder="Rechercher"></h2>
            </div>
            <table id="manif-table" class="table-hover">
                <thead>
                    <tr>
                        <th>Formulaire</th>
                        <th>Date de début</th>
                        <th>Nom</th>
                        <th>Départ de</th>
                        <th>Délai</th>
                        <th>État</th>
                        <th>Complétude</th>
                        <th>Dernière action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for manif in object_list %}
                        {# onclick dans le <tr> ne marche pas avec bootstrap-table, voir script main. On passe l'url avec data-href #}
                        <tr class="{% if manif.get_cerfa.instruction %}
                                        {% if manif.get_cerfa.instruction.etat == 'interdite' %}
                                            table-danger
                                        {% elif manif.get_cerfa.instruction.etat == 'autorisée' %}
                                            table-success
                                        {% elif manif.get_cerfa.instruction.etat == 'annulée' %}
                                            table-secondary
                                        {% else %}
                                            table-info
                                        {% endif %}
                                    {% else %}
                                        table-warning
                                    {% endif %} clickligne"  data-href='{{ manif.get_cerfa.get_absolute_url }}'>
                            <td>{% include 'evenements/pictos/type_evenement.html' %}</td>
                            <td >{{ manif.date_debut| date:"d/m/Y" }}</td>
                            <td>{{ manif.nom }}</td>
                            <td>{{ manif.ville_depart }}</td>
                            <td>{% if manif.get_type_manif %}
                                {% include 'evenements/pictos/delai.html' %}
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {% include 'evenements/pictos/etat.html' %}
                            </td>
                            <td>{% if manif.get_type_manif %}
                                    {% if manif.get_cerfa.dossier_complet %}
                                        {% if manif.instruction.doc_verif %}
                                            <i class="dossier-complet-verifie" data-nb_jour='{{ manif.get_cerfa.delai_en_cours }}'></i>
                                        {% else %}
                                            <i class="dossier-complet-non-verifie" data-nb_jour='{{ manif.get_cerfa.delai_en_cours }}'></i>
                                        {% endif %}
                                    {% else %}
                                        <i class="dossier-incomplet" data-nb_jour='{{ manif.get_cerfa.delai_en_cours }}'></i>
                                    {% endif %}
                                {% endif %}
                            </td>
                            <td>{{ manif.actions.last.creation_date|date:"d/m/Y H:i" }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td></td>
                            <td>Aucune manifestation déclarée pour le moment</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="well">
            <p>Dans un premier temps, veuillez renseigner les informations relatives à la structure organisatrice de la manifestation sportive</p>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <a href="{% url 'events:structure_add' %}" class="btn btn-primary" role="button">
                    Accéder au formulaire de renseignement sur la structure organisatrice
                </a>
            </div>
        </div>
    {% endif %}
    <script>

            $('body').on('click', 'tr.clickligne', function (event) {
                window.location=$(this).data("href");
            });

        $(document).ready(function () {
            $.fn.dataTable.moment( 'DD/MM/YYYY' );
            $.fn.dataTable.moment( 'DD/MM/YYYY HH:mm');
            $('#manif-table').DataTable({
                "paging": false,
                "info": false,
            });
            $('.dataTables_filter').hide();

            $("#search").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#manif-table tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
{% endblock %}

evenements/templates/evenements/documentcomplementaire_form_new.html
{% load static clever_selects_extras file_tags thumbail_filter i18n %}
<h5>Listes des informations complémentaires demandées :</h5>

<form class="form-horizontal" id="form_doc_compl" action="{% url 'evenements:repondre_doc_complementaire' pk=pk %}"
      enctype="multipart/form-data" method="post">
    {{ forms.management_form }}
    {% csrf_token %}
    <ul class="list-group">
        {% for form in forms %}
            <li class="list-group-item" style="margin-bottom: 1em;">

                {% for field in form %}

                    {% if field.field.widget.input_type == textarea %}
                        Demande :
                        <blockquote>
                            {% if form.instance.document_attache %}<i class="ok "></i>
                            {% else %}<i class="action-requise "></i>{% endif %}
                            {{ field.value }}</blockquote>
                        <div style="display: none">{{ field }}</div>
                    {% elif field.field.widget.input_type == 'hidden' %}
                        {{ field }}
                    {% else %}
                        {% if form.instance.document_attache %}
                            Réponse :  <a href="{{ form.instance.document_attache.url }}">{{ form.instance.document_attache.name|basename }}</a>&nbsp;&nbsp;
                            <span data-toggle="tooltip" data-placement="auto" data-html="true" class="badge badge-info"
                                  title="<img src='{{ form.instance.document_attache|thumbnail }}'"><i class="deplier no-right-margin text-white"></i>
                            </span>
                        {% else %}
                            <div>{{ field }}</div>
                        {% endif %}
                    {% endif %}

                {% endfor %}

            </li>
        {% endfor %}
    </ul>
    {% if not done %}
        <input type="submit" class="btn btn-primary" value="Enregistrer">
    {% endif %}
</form>

<script src="{% static 'portail/js/icone.js' %}" type="text/javascript"></script>

evenements/templates/evenements/evenement_carto_form.html
{% load crispy_forms_tags %}
{% load i18n verbose_tags %}
{% load static %}


    <script src="{% static 'portail/js/main.js' %}" type="text/javascript"></script>


    <form class="form-horizontal" action="{% url 'evenements:manif_carto' pk=form.instance.id %}" method="post" enctype="multipart/form-data" id="manifestation-form">
        {% if form.target.id %}<input type="hidden" name="id" id="id_id" value="{{ form.target.id }}">{% endif %}
        {% crispy form %}
        {{ form.media }}
        <div class="form-actions">
            <input id="submit-id-save" class="btn btn-primary" type="submit" value="Enregistrer" name="save">
            </input>
            {% if form.instance.id %}
                <a class="btn btn-danger" id="carto_annul" href="javascript:history.back()">Annuler</a>
            {% endif %}

        </div>
    </form>
    <script src='{% static "portail/js/file-validator.js" %}' type="text/javascript"></script>
    <script src='{% static "libs/autogrow/jquery.ns-autogrow.min.js" %}' type="text/javascript"></script>
    <script src='{% static "portail/js/jquery.liveValidation.js" %}' type="text/javascript"></script>
    <script src='{% static "evenements/js/manifestation_formulaire.js" %}' type="text/javascript"></script>
{#    <script>jQuery.fn.preventDoubleSubmission = function(){}</script>#}